UniProt  в европейском сайте биоинфы получше чем NCBI, ттем что там загружены кристаллы полученные с помощью рентгеноструктурного анализа, можно повертеть посмотреть

геномные браузеры - вбиваем название гена, и переходим в браузер, вверху хромосома

мелкие черточки и жирные - экзоны, все что между это интроны

GeneCards

# №1

In [ ]:
s = 'ATGAGTCTCT'
s1 = 'CTGTCTCCTG'
sub = {'A': 'T', 'T': 'A', 'G':'C', 'C':'G'}
s1 = ''
for i in s:
  s1 += sub[i]
s1[::-1]

'AGAGACTCAT'

# №2

\begin{array}{c|c|c|c|c|c|c|}
& & A & T & G & A & T & G & C & T & C & T \\ \hline
& 0 & -10 & -20 & -30 & -40 & -50 & -60 & -70 & -80 & -90 & -100 \\ \hline
C & -10 & \searrow~-4 & \rightarrow~-14 & \rightarrow~-24 & \rightarrow~-34 & \rightarrow~-44 & \rightarrow~-54 & \searrow~-55 & \rightarrow~-65 & \rightarrow~-75 & \rightarrow~-85\\ \hline
T & -20 & \downarrow~-14 & \searrow~1 & \rightarrow~-11 & \rightarrow~-21 & \searrow~-29 & \rightarrow~-39 & \rightarrow~-49 & \searrow~-50 & \rightarrow~-60 & \searrow~-70 \\ \hline
G & -30 & \downarrow~-24 & \downarrow~-9 & \searrow~6 & \searrow~-4 & \rightarrow~14 & \searrow~-24 & \rightarrow~-34 & \rightarrow~-44 & \rightarrow~-54 & \rightarrow~-64 \\ \hline
T & -40 & \downarrow~-34 & \searrow~-19 & \\ \hline
C & -50 & \downarrow~-44 & \downarrow~-29 & \\ \hline
T & -60 & \downarrow~-54 & \searrow~-39 & \\ \hline
C & -70 & \downarrow~-64 & \downarrow~-49 & \\ \hline
C & -80 & \downarrow~-74 & \downarrow~-59 & \\ \hline
T & -90 & \downarrow~-84 & \searrow~-69 & \\ \hline
G & -100 & \downarrow~-94 & \downarrow~-79 & \\ \hline
\end{array}


# №4

In [113]:
import numpy as np
s = 'ATGATGCTCT'
s1 = 'CTGTCTCCTG'
n, m = len(s) + 1, len(s1) + 1

a = np.zeros((m, n))
for j in range(1, n):
  a[0][j] = a[0][j - 1] - 10
for i in range(1, m):
  a[i][0] = a[i - 1][0] - 10

for i in range(1, m):
  for j in range(1, n):
    c = 5 if s[j - 1] == s1[i - 1] else -4
    a[i][j] = max(a[i][j - 1] - 10, a[i - 1][j] - 10, a[i - 1][j - 1] + c)
for i in range(m):
  print(a[i])

[   0.  -10.  -20.  -30.  -40.  -50.  -60.  -70.  -80.  -90. -100.]
[-10.  -4. -14. -24. -34. -44. -54. -55. -65. -75. -85.]
[-20. -14.   1.  -9. -19. -29. -39. -49. -50. -60. -70.]
[-30. -24.  -9.   6.  -4. -14. -24. -34. -44. -54. -64.]
[-40. -34. -19.  -4.   2.   1.  -9. -19. -29. -39. -49.]
[-50. -44. -29. -14.  -8.  -2.  -3.  -4. -14. -24. -34.]
[-60. -54. -39. -24. -18.  -3.  -6.  -7.   1.  -9. -19.]
[-70. -64. -49. -34. -28. -13.  -7.  -1.  -9.   6.  -4.]
[-80. -74. -59. -44. -38. -23. -17.  -2.  -5.  -4.   2.]
[-90. -84. -69. -54. -48. -33. -27. -12.   3.  -7.   1.]
[-100.  -94.  -79.  -64.  -58.  -43.  -28.  -22.   -7.   -1.   -9.]


# №5

In [114]:
import numpy as np
s = 'AGTACGCA'
s1 = 'TATGC'
n, m = len(s) + 1, len(s1) + 1

a = np.zeros((m, n))
for j in range(1, n):
  a[0][j] = a[0][j - 1] - 10
for i in range(1, m):
  a[i][0] = a[i - 1][0] - 10

for i in range(1, m):
  for j in range(1, n):
    c = 5 if s[j - 1] == s1[i - 1] else -4
    a[i][j] = max(a[i][j - 1] - 10, a[i - 1][j] - 10, a[i - 1][j - 1] + c)

Вывод оптимального выравнивания

In [115]:
i, j = len(s1), len(s)
al_s, al_s1 = '', ''
while i > 0 and j > 0:
  c = 5 if s[j - 1] == s1[i - 1] else -4
  if a[i][j] == a[i - 1][j - 1] + c:
    al_s = s[j - 1] + al_s
    al_s1 = s1[i - 1] + al_s1
    i, j = i - 1, j - 1
  elif a[i][j] == a[i - 1][j] - 10:
    al_s = '-' + al_s
    al_s1 = s1[i - 1] + al_s1
    i = i - 1
  else:
    al_s = s[j - 1] + al_s
    al_s1 = '-' + al_s1
    j = j - 1

while j > 0:
  al_s = s[j - 1] + al_s
  al_s1 = '-' + al_s1
  j = j - 1

while i > 0:
  al_s = '-' + al_s
  al_s1 = s1[i - 1] + al_s1
  i = i - 1

print(al_s)
print(al_s1)

AGTACGCA
--TATGC-
